### ISSUE TITLE
Feature - Button to Speed up moon cycles

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#14]
This would require code changes. It is currently CPU limited... Would we even be able to speed it up? Or would we want to make it a fixed update speed and people would need to speed up their DOSBox clock for us to have some headroom to work with.

Idea from dagit

**Comment by cambragol** [comment]
In Boxer, on Mac, this can already be done by simply hitting the fast forward key. PC DOSBox must surely have this feature as well?

**Comment by Fenyx4** [comment]
That is an excellent point. That can be done with ctrl+F12 and slowed down again with ctrl+F11 in Dosbox. I'm gonna close this issue.
