### ISSUE TITLE
Feature - Randomize reagents of spells you learn in the game

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#25]
See changing a spell recipe here; https://github.com/Fenyx4/U4DosRandomizer/blob/master/U4DosRandomizer/Program.cs#L144

Change the in game hint here;
https://github.com/Fenyx4/U4DosRandomizer/blob/master/U4DosRandomizer/Talk.cs#L55
https://wiki.ultimacodex.com/wiki/Ultima_IV_transcript

**Comment by cambragol** [comment]
This goes against the prose in the Book of Spells. Which seems nearly on par with the changing of mantras to me.

Maybe limit it to spells that are not revealed initially in the book of spells. That way discovering their recipe becomes something that must be done again, not just looked up in a wiki.

**Comment by Fenyx4** [comment]
Agreed. "not revealed initially in the book of spells" was what I meant by "spells you learn in the game".

I dunno how randomizing them all would even work. I'd need to add a bunch of NPCs just to give the player the all the recipes.

**Comment by cambragol** [comment]
I think I read that wrong. Randomizing of spells you learn in game seems clear enough! Haha

**Comment by Fenyx4** [comment]
9b60bf03545a8218eae4cbca19249d81c08e8ca6
