### ISSUE TITLE
Castles Right Next to Each Other

### ISSUE THREAD

**Issue by cambragol** [Fenyx4/U4DosRandomizer#26]
This is for the latest version, Release v0.2-alpha.1

I found two castles right next to each other:

![Ultima IV Randomized 2020-09-06 at 7 52 56 PM](https://user-images.githubusercontent.com/5019739/92324345-d0073b80-f07b-11ea-8d3e-054e99696b6c.png)

**Comment by cambragol** [comment]
Still getting this on the latest release. Also dungeons in close proximity, and shrines.

![Ultima IV Randomized 2020-09-16 at 2 19 03 PM](https://user-images.githubusercontent.com/5019739/93295350-c6be6180-f827-11ea-9768-3c53b934f616.png)
![Ultima IV Randomized 2020-09-16 at 2 18 58 PM](https://user-images.githubusercontent.com/5019739/93295356-c920bb80-f827-11ea-986b-c21f2c45717c.png)
![Ultima IV Randomized 2020-09-16 at 2 14 24 PM](https://user-images.githubusercontent.com/5019739/93295364-ccb44280-f827-11ea-946d-64152c323fa0.png)

**Comment by Fenyx4** [comment]
Done!
Haven't pushed a new version for it yet. Wanna get a few more things added before I do. But if you want this change sooner let me know and I can push a new version for you.
