### ISSUE TITLE
Very Straight Unnatural Rivers

### ISSUE THREAD

**Issue by cambragol** [Fenyx4/U4DosRandomizer#27]
Found rivers that have very long straight sections.

![Ultima IV Randomized 2020-09-06 at 7 56 54 PM](https://user-images.githubusercontent.com/5019739/92324455-ce8a4300-f07c-11ea-9c8c-a4f265bc19c7.png)
![Ultima IV Randomized 2020-09-06 at 7 57 07 PM](https://user-images.githubusercontent.com/5019739/92324458-d2b66080-f07c-11ea-8982-b2ee2184c8bf.png)

**Comment by Fenyx4** [comment]
This will be fixed in next version. I improved mountains that made it worse so had to fix it now.
