### ISSUE TITLE
Ejection from the Abyss

### ISSUE THREAD

**Issue by cambragol** [Fenyx4/U4DosRandomizer#30]
Ejection from the Abyss results in being sent to one of several places, depending when you are ejected. I think you are sent either to the entrance to the abyss itself, or else several locations near the staring towns.

Here is the code:

unsigned char D_0BF0[] = {0xE7,0x53,0x23,0x3B,0x9E,0x69,0x17,0xBA,0xD8,0x1D,0x91,0x59,0xE9};
unsigned char D_0BFE[] = {0x88,0x69,0xDD,0x2C,0x15,0xB7,0x81,0xAC,0x6A,0x30,0xF3,0x6A,0xE9};

static unsigned D_8CCA;

/*return to surface*/
C_2F9D(bp04)
unsigned bp04;
{
	u_delay(5, 0);
	Gra_CR();
	Party._x = D_0BF0[bp04];
	Party._y = D_0BFE[bp04];
	Party.f_1d8 = D_8CCA;
	Party._loc = 0;
	CurMode = MOD_OUTDOORS;
	spell_cnt = 0;
	hit_tile = 0;
	spell_sta = 7;
	D_9440 = 1;
	D_95C6 = 0;
	Party.f_1dc = 0;
	C_26B6();
	dspl_Stats();
	u_kbflush();
	longjmp(D_9458, -1);
}

The values in D_0BF0[] and D_0BFE[] will need to be tweaked to match any changes to the map, town locations.

**Comment by cambragol** [comment]
Has this been dealt with in U4DosRandomizer yet?

**Comment by Fenyx4** [comment]
I caught the Abyss location in that list but didn't catch the others. For some reason when I looked at the code before I thought it was was teleporting to different locations in the Abyss. Not sure why I thought that...

I'm working on get myself setup to make code changes to AVATAR.EXE. Once I have that all working I will circle back to this.

**Comment by cambragol** [comment]
I believe it is sending you to the various towns and castles (near them) to 'brush up' on your knowledge of that virtue/principle if you don't answer them correctly.
So, Moonglow, Britain, Jhelom, Yew, Minoc, Trinisic, Skara Brae, Magincia, Lycaeum, Empath Abbey then Serpents Hold.

**Comment by Fenyx4** [comment]
This should be fixed! New release https://github.com/Fenyx4/U4DosRandomizer/releases/tag/v0.2-alpha.2
