### ISSUE TITLE
Fix healer in Serpent's Hold

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#38]

**Comment by cambragol** [comment]
The Healer doesn't work? That's a new bug...isn't it?

**Comment by Fenyx4** [comment]
Nope. Doesn't work in the base install from GOG.

**Comment by Fenyx4** [comment]
Got me curious now. Booting up my original disks.

**Comment by cambragol** [comment]
I just checked in Trinity, also broken...but should be working...

**Comment by Fenyx4** [comment]
Yeah. Broken on my original DOS disks.

I need to get a good Apple ii save so I can more easily check things like this...

**Comment by cambragol** [comment]
Okay, I fixed in Trinity.

I have the apple II disks if you need, with three saves, though no uber parties.

**Comment by cambragol** [comment]
https://www.foumartgames.com/play/83-Ultima-IV.html

**Comment by cambragol** [comment]
<img width="578" alt="Screen Shot 2020-11-29 at 13 28 34" src="https://user-images.githubusercontent.com/5019739/100533366-e241e180-3246-11eb-813c-e570f85bdad3.png">

**Comment by cambragol** [comment]
Looks like it existed in Apple II version too!

**Comment by Fenyx4** [comment]
Note to self change
https://github.com/ergonomy-joe/u4-decompiled/blob/c2c2108fa3bb346bcd1d8c207c526f33a4c8f5ef/SRC/U4_TALK.C#L333 
from 0x0C to 0x12.

**Comment by Fenyx4** [comment]
Nice! Thanks for checking that.

**Comment by Fenyx4** [comment]
And yay fixed in Trinity!

**Comment by Fenyx4** [comment]
I just checked and it works in the Sega Master System version. :)

**Comment by cambragol** [comment]
Sega!?! That version doesn't even count! ;)
