### ISSUE TITLE
Fix Sacrifice

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#41]
Make it gain when giving the last coin

**Comment by cambragol** [comment]
Is that what Hawkwind tells you, or is that from a shrine vision. I was sure I went through and checked that all the visions and advice from hawkwind were reflected in karma gains/losses, but I can't remember that one.

**Comment by cambragol** [comment]
Ah, I see it now. Shrine vision.

**Comment by Fenyx4** [comment]
Yeah, I have been watching a first playthrough and someone is hooked on the idea of lowering sacrifice this way. 😢

**Comment by cambragol** [comment]
ouch.

**Comment by cambragol** [comment]
This is in Trinity now.

**Comment by Fenyx4** [comment]
Arg. I just tested this in Apple and it increases Honor not Sacrifice.

Best idea is that it is a bug in the Apple II version and that it was "fixed" in DOS by removing it entirely.

I'm still gonna fix it by making it Sacrifice.

**Comment by cambragol** [comment]
It should be Sacrifice. The Shrine vision indicates that, and most other shrine visions and advice from Hawkwind is reflected correctly in karma gains/losses.

**Comment by Fenyx4** [comment]
Agreed. It is just weird that no version that I have checked got it right.
