### ISSUE TITLE
Include Conversation fixes from U4 Remastered (C64)

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#45]
https://github.com/MagerValp/u4remastered/blob/master/Changelog.txt

* Fixed broken question trigger and added missing dialogue for Thevel in Britain.
     - Already fixed in DOS
* Added missing dialogue for Serpent's Hold gate guards.
    - Fixed in #43
* Changed keyword for Michelle to avoid conflict with health in Serpent's Hold.
    - Already fixed in #40 but should check how they fixed it
* Fixed broken message trigger for Water in Castle British.
   - Fixed in #43
* Fixed misspelled keyword for Estro in the Lycaeum.
   - REAS -> RESE
* Fixed misspelled keyword for a poor beggar in Yew.
   - Already fixed in DOS
* Fixed broken message trigger for Alkerion in Minoc.
   - #43
* Fixed broken message trigger for Shamino in Skara Brae.
   - #43
* Fixed broken message trigger for Charm in Cove.
  - #43
* Dozens of minor fixes to spelling, grammar, and formatting. 
  - Hard to track these down... Maybe I could output the talk files to json to match their format and compare? 
  https://github.com/MagerValp/u4remastered/blob/551c5adee07917094d63d88477eec5790e3b18a0/src/talk/talk.json

**Comment by Fenyx4** [comment]
https://github.com/MagerValp/u4talk This will help!

http://htmlpreview.github.io/?https://github.com/MagerValp/u4talk/blob/master/talk.html

**Comment by MagerValp** [comment]
Just stumbled over this. Happy you're finding my fixes useful!

**Comment by Fenyx4** [comment]
They are great! And your talk table was invaluable.

I submitted a PR to add the SMS version to the table too! 
http://htmlpreview.github.io/?https://github.com/fenyx4/u4talk/blob/master/talk.html
