### ISSUE TITLE
Speedup Features - Start with quest items

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#48]
Option to start with random amount, % chance to have them on slider (so 100% would be guaranteed to start with all of them)
Each one with separate slider?

Runes
Stones
Three Part Keys
Bell, Book, Candle

**Comment by cambragol** [comment]
but...but...why even play the game then?

**Comment by Fenyx4** [comment]
It is a request from Twitch Streams. They want to be able to play the entire game/randomized game in a shorter amount of time to fit in a single stream. Shorter also opens the possibility of streamers racing each other. Which would be cool if it ever happened.

**Comment by cambragol** [comment]
...okay... ?

**Comment by Fenyx4** [comment]
*shrugs* There are lots of options to make things harder. I am okay with adding some to make it easier too. Then people can mix and match the options to their heart's content.

**Comment by Fenyx4** [comment]
This is done.
