### ISSUE TITLE
Awaken effect whole party

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#76]
Awaken is not used often.
Making it effect whole party would make it very useful.

https://github.com/Fenyx4/U4DosRandomizer/blob/master/u4_decompile/SRC/U4_SPELL.C#L147

Idea from organmike

**Comment by cambragol** [comment]
I like this one. There are other spells that could use a tweak too, as they are almost never used.

**Comment by cambragol** [comment]
An additional tweak would be a lasting effect. I.e., a spell status that KEEPS the party awake and protects against further sleep spells for a couple of turns.

**Comment by Fenyx4** [comment]
https://github.com/Fenyx4/U4DosRandomizer/tree/awaken
