### ISSUE TITLE
Saving in Towns

### ISSUE THREAD

**Issue by cambragol** [Fenyx4/U4DosRandomizer#82]
How about it?

Was thinking on it because of the size of some random encounters in ToTT.

**Comment by Fenyx4** [comment]
That would be pretty cool. I'll have to see if there is a way to squeeze this into the existing save file or look at other options.

You added a separate .SAV file, right?

**Comment by cambragol** [comment]
Yeah, I added a separate .sav file. However, 99% of additions were squeezed into the player.sav file, enough that the game is still 100% compatible with default. I stored data on extra bits within single bytes.

I looked at saving in towns before, and I think it would be possible relatively easily. You would just need some code to 'setup' the player in the town on load. You might also need to store the x y coordinates of the player. Fancy would be to also store the x y of the npcs, but not really critical.

**Comment by Fenyx4** [comment]
Okay... That was a lot easier than I thought.
https://github.com/Fenyx4/U4DosRandomizer/tree/save-town
There is a bug there with open doors being completely gone on a save/reload. But otherwise it looks pretty good. I'll look into fixing that soon. Maybe see if I can close all the doors before doing the save.

Do you have a fix for the "If file doesn't exist then it crashes" problem? Or do you just have your ITEMS.SAV be pre-existing?

**Comment by cambragol** [comment]
You build the new files into title.exe, where they are converted from a newsave.new into a 'newsave.sav'...I think. At least I did that for 'karma.sav' (which is the new version of items.sav which has new stuff saved to it)

My other two save files, which handle saving in the underdeep, and moving in and out of towns in the undeerdeep, are just preexisting. Though, thinking about it now, I may need to make an underdeep version of the monsters.sav, otherwise a player would load a previous save when entering the underdeep for the first time,...I think..better double check that.

**Comment by cambragol** [comment]
That looks about as easy as I thought it might be. I guess I never pursued it because I was trying to stay truer to Apple II roots. However, as I mentioned at the top of this thread, large 'town' encounters might necessitate adding this in for me too. I'll probably grab your code for that. Hahah! 

Missing doors sounds weird though..

**Comment by Fenyx4** [comment]
It ain't pretty but I fixed the missing doors problem.
7ffcd5a0846b1e0a94c1e7b5a137a0103bd949ac

Could be made prettier by exposing D_17FE or by adding a function to U4_EXPLO.C and doing;
```
while(D_17FE)
	C_431D();
```

**Comment by cambragol** [comment]
I'm going to try it in Tott. What is C_3E30 though? My code has deviated quite a bit, and my functions are all renamed. I can't find that function in your code either.

**Comment by cambragol** [comment]
Wait, that must just be the town loading code...

**Comment by cambragol** [comment]
Hmm...couldn't copy your code exactly, but functionally I got the same thing going on. And my doors load fine.

Hm.

**Comment by cambragol** [comment]
Well, I have mine working, with multi-level saves, and restoring to any location or level in the town. Looks good so far, and very low low code cost.

I wonder how to account for your issues with the doors though...

**Comment by cambragol** [comment]
Mine is missing moons and wind on load. For you, moons might not show, as they are not updated in towns?

**Comment by cambragol** [comment]
I think you can fix the wind issue (if you are having it) by making a quick call to the animate wind function on load game. Simple stuff. It'll animate, then freeze because the location is a building. Without this call the moons zone is empty, because moons are turned off in town, and the moon area is not updated in towns, so the last moon state just remains when entering a town.

**Comment by Fenyx4** [comment]
Door bug recreation steps.
1) open door
2) save before the door closes
3) reload the game

I will look at the moon's and winds later.

**Comment by Fenyx4** [comment]
Yes C3E30 is the town load.

https://github.com/Fenyx4/U4DosRandomizer/blob/a92b120d22364b8afeb8836fd67838f45703a137/u4_decompile/SRC/U4_EXPLO.C#L34

**Comment by cambragol** [comment]
Okay, I see the bug now. Mine has it too of course.

**Comment by cambragol** [comment]
I found a different fix.

Rather than use:

unsigned D_17FA = 0;/*current opened door's x*/
unsigned D_17FC = 0;/*current opened door's y*/

to record the x,y of the door, I store it in these positions:

D_8742._npc._old_x[30]
D_8742._npc._old_y[30]

Then on loading the townmap.sav, I call this:

D_8742._map.x32x32[D_8742._npc._old_y[30]][D_8742._npc._old_x[30]] = TIL_Door_3B;

You could even add a delay to the above, if you wanted to get fancy. Otherwise the doors are just closed on load.

**Comment by cambragol** [comment]
Problem though. old_x and old_y are normally not used in the 'town' file. But now they are when saving. So the above won't really work, as it is interfering with one of the NPCs x,y info.

**Comment by cambragol** [comment]
It might though...

**Comment by cambragol** [comment]
I stored D_17FE in the save file at another npc's old_y position and now I have the doors close with the correct delay on load. So the entire state of the town is saved and restored. I'm still wondering whether hijacking the old_x and old_y slots for two NPCs will cause any problems...It might just be that their next movement is a little wonky.

**Comment by cambragol** [comment]
I tested NPCs who were having their old_y and old_x hijacked for the door code, and saw no adverse affects.

**Comment by cambragol** [comment]
I went a different route in order to get the results without any new code. I utilized my existing Karma.sav file to store all the relevant variables for saving/loading. I also had to contend with my 'horse code', which preserves horses when traveling between floors (which, but the way, is a bug in DOS u4 -- riding a horse into British's castle, then moving up and down the ladder, deletes the horse)

I don't think my solutions will work for your code, unfortunately.

**Comment by Fenyx4** [comment]
No worries. Glad we both have a solution.

Although I'm definitely gonna have to look at the horse. A) make sure it saves and B) maybe I can fix the horse disappearing issue too.

It had never occurred to me to fix the horse disappearing bug. It has always just been a thing. Rain is wet. Things fall down. Horses disappear if you take them in when visiting Lord British.

**Comment by cambragol** [comment]
I had to deal with the horse because of all the new up and down movement in Tott. Otherwise I probably would have thought like you. And just learn to leave my horse outside the castle. I did add comment to that effect for all the shops in Tott. I.e. The 'Get that horse outta here!' reaction is for all shops, not just the...er...inn?

For your code, there are a couple of save variable you could hijack to get stuff done. The shrine and camping cool-down variables can totally be used, because they are not used once you are in a town. Or are no longer important. You could utilize those to save some info for the horse/doors.

**Comment by cambragol** [comment]
Saving the whole town this way makes me wonder about a new mod/game using Ultima IV's base, where every town and its characters are saved on each visit. Add in a couple of more variables for each character and you could have a very different game with complex quest triggers and world permanence/change. Kind of like Fallout, where every character is 'killable' and that possibility is built into the game. Not very Ultima IVy,  but certainly a bit like Ultima V. Maybe we could convert Ultima IV into Ultima V...
